#!/bin/bash

#urls are configured and mapped with the desired outfile name. Each url is opened in a phantom(headless browser) instance, included css files
#are identified from the DOM, each css file is read(from the local copy in styles directory) and its content is appended to the output file. 
#Once the single required css file is ready, penthouse.js is called to generate the above the fold css. Generated above the fold files will be copied 
#to codebase. Users can just go-ahead and commit the files.

#Css for a single url can be generated by passing the url as an argument
#  Ex: bash generateAboveTheFoldCss.sh http://localhost:8080/loan.html
#If no url is passed as a param, css will be generated for all the preconfigured list of urls

if [[ $1 == "--help" || $# -eq 0 || $1 == *"html"* ]];then
	printf "%s\n"
        printf "%s\n%s\t" "Usage:"
	printf "%s\n%s\n%s\t" "bash generateAboveTheFoldCss.sh <serverurl>"
        printf "%s\n%s\n%s\t" "Ex:bash generateAboveTheFoldCss.sh http://localhost:8080"
        printf "%s\n%s\n%s\t" "If you want to generate above the fold for a particular url then you could do like below "
        printf "%s\n%s\n%s\t" "bash generateAboveTheFoldCss.sh <serverurl> <pageurl>"
        printf "%s\n%s\n" "Ex:bash generateAboveTheFoldCss.sh http://localhost:8080 http://localhost:8080/loan.html"
	exit 1
else 
	serverurl=$1
	lastcharindex=$((${#serverurl}-1))
	lastchar=${serverurl:$lastcharindex}
	#remove the last slash if the input is http://localhost:8080/
	if [ $lastchar == "/" ];then
	  serverurl=${serverurl:0:$lastcharindex}
	fi
fi



serverResponse=`wget --spider --server-response --max-redirect=0 $serverurl 2>&1`
if [[ $serverResponse == *"Connection refused"* ]]
   then
      echo "Looks like the server is down, please start the server and run me again!!"
      exit 1
fi


HOME_DIR=`pwd`
SOURCE_DIR=`pwd`/styles
PENTHOUSE_DIR=`pwd`/penthouse-master
ABOVE_FOLD_DIR=`pwd`/above_the_fold
OUTPUT_DIR=`pwd`/output
cd
MP_CODEBASE_DIR=`pwd`/code-base/central-repo/websites/marketplace/src/main/webapp/styles
CORE_CODEBASE_DIR=`pwd`/code-base/central-repo/websites/website-core/src/main/webapp/styles


#add new entries to this map when you want to generate above the fold css for a new url
declare -A urls=( ['/']="gateway.css"
					['/loan.html']="loan.css"
					['/select.html']="select.css"
					['/personal-loan.html']="personal-loan.css"
					['/car-loan.html']="car-loan.css"
					['/home-loan.html']="home-loan.css"
					['/personal-loan.html?catStyleNeeded=true']="personal-loan-slide.css"
					['/car-loan.html?catStyleNeeded=true']="car-loan-slide.css"
					['/home-loan.html?catStyleNeeded=true']="home-loan-slide.css"
					['/hdfc-personal-loan.html']="lw-personal-loan-fold.css"
					['/axis-home-loan.html']="lw-home-loan-fold.css"
					['/axis-car-loan.html']="lw-car-loan-fold.css"
					['/credit-card.html']="credit-card.css"
					['/credit-card.html?variant=slide']="credit-card-slide.css"
					['/american-express-credit-card.html']="lw-credit-card-fold.css"
					['/insurance.html']="insurance.css"
					['/insurance/life-insurance.html']="life-insurance.css"
					['/insurance/health-insurance.html']="health-insurance.css"
					['/insurance/car-insurance.html']="car-insurance.css"
					['/insurance/aegon-religare-life-insurance.html']="lw-term-life-insurance-fold.css"
					['/insurance/apollo-munich-health-insurance.html']="lw-health-insurance-fold.css"
					['/insurance/bajaj-allianz-car-insurance.html']="lw-car-insurance-fold.css"
					['/fixed-deposit.html']="lw-fixed-deposit-fold.css"
					['/fixed-deposit-rate.html']="lw-fixed-deposit-rate.css"
					['/ifsc-code.html']="ifsc-code-landing.css"
					['/ifsc-code/hdfc-bank.html']="ifsc-code-bank.css"
					['/ifsc-code/hdfc-bank/tamil-nadu.html']="ifsc-code-state.css"
					['/ifsc-code/hdfc-bank/tamil-nadu/chennai.html']="ifsc-code-city.css"
					['/ifsc-code/hdfc-bank/tamil-nadu/chennai/chennai-nungambakkam-branch.html']="ifsc-code-branch.css"
					['/finance-tools/emi-calculator.html']="emi-calculator.css"
					['/finance-tools/personal-loan-emi-calculator.html']="emi-calculator-pl.css"
					['/finance-tools/car-loan-emi-calculator.html']="emi-calculator-cl.css"
					['/finance-tools/home-loan-emi-calculator.html']="emi-calculator-hl.css"
					['/aboutus.html']="aboutus.css"
					['/aboutus.html#careers']="careers.css")

#setup start
cd $HOME_DIR
find -iname *.css -delete

#copy all the css with directory structure from codebase
cd $MP_CODEBASE_DIR
  cp -R * $SOURCE_DIR

cd $CORE_CODEBASE_DIR
cp -R * $SOURCE_DIR
#setup end

#find and concatenate the required css --> pass it to penthouse to generate the critical css --> pass it to cssminifier to minify the css
cd $HOME_DIR

if [ $# -eq 2 ]
  then
    inputurl=$2
    url=${inputurl:21}
    declare -A urls=([$url]=${urls["$url"]})
fi

errorurls=
for key in "${!urls[@]}"
do
        fullurl=$serverurl$key
        outputFile=${urls["$key"]}
        if [ -z "$outputFile" ];then
            echo "No entry found for the url" $fullurl
	    echo "If you are trying to generate css for a url that is not in the preconfigured list, please add an entry in urls map and then run me again"
            exit 1
        fi
        echo "Starting to generate css for $fullurl"
	phantomjs buildRequiredCss.js $fullurl $outputFile
        if [  -f $OUTPUT_DIR/$outputFile ]; then
		echo "Source css generated"
		phantomjs $PENTHOUSE_DIR/penthouse.js $fullurl $OUTPUT_DIR/$outputFile > $ABOVE_FOLD_DIR/$outputFile
		echo "Above the fold css generated"
		node $HOME_DIR/minifycss.js $ABOVE_FOLD_DIR/$outputFile 
        	echo "css minified"
        else 
                errorurls+=$fullurl", "
	fi
        echo "============================================"

done

#copy the generated css to codebase directory
if [ -z "$errorurls" ]; then
        #no errors, so proceeding to copy the files
	cp $ABOVE_FOLD_DIR/* $MP_CODEBASE_DIR/above_the_fold
	echo "CSS files copied to codebase!!, Go ahead and commit the files"
else
        echo "***************************************************************************"
        echo "Issues have occured while generating above the fold css for the below urls"
        echo "============================================================================"
        echo $errorurls
        echo "============================================================================"
        echo "Files have not been copied to codebase, please fix the errors and run me again"
	echo "****************************************************************************"
fi

